import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  header: {flexDirection: 'row', justifyContent: 'space-between', margin: 20},
  headerIcon: {
    height: 30,
    width: 30,
    tintColor: '#F9A46C',
  },
  searchIcon: {
    height: 30,
    width: 30,
    tintColor: 'white',
    marginRight: 10,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F9A46C',
    margin: 20,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
  },
  searchTextInput: {color: 'white', fontSize: 20},
  categoryMenu: {
    flexDirection: 'row',
    marginHorizontal: 20,
    justifyContent: 'space-around',
  },
  buttonPress: {
    backgroundColor: '#F9A46C',
    borderRadius: 15,
    paddingHorizontal: 30,
    paddingVertical: 8,
  },
  buttonUnPress: {
    borderWidth: 1,
    borderColor: '#F9A46C',
    borderRadius: 15,
    paddingHorizontal: 30,
    paddingVertical: 8,
  },
  textPress: {
    fontSize: 16,
    fontWeight: '700',
    color: 'white',
  },
  textUnPress: {
    fontSize: 16,
    fontWeight: '700',
    color: '#F9A46C',
  },
  list: {margin: 20},
  grup: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 10,
  },
  grupProduct1: {
    backgroundColor: '#F9A46C',
    borderRadius: 25,
    paddingVertical: 20,
    paddingHorizontal: 12,
  },
  grupProduct2: {
    backgroundColor: 'white',
    borderRadius: 25,
    paddingVertical: 20,
    paddingHorizontal: 12,
    shadowOffset: {height: 10, width: 10},
    elevation: 5,
    shadowColor: 'black',
    shadowOpacity: 0.8,
  },
  grupProductImage: {
    width: 150,
    height: 150,
  },
  productIcon1: {width: 15, height: 15, tintColor: '#F9A46C'},
  productIcon1Bar: {
    padding: 5,
    backgroundColor: 'white',
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  productIcon2: {width: 15, height: 15, tintColor: 'white'},
  productIcon2Bar: {
    padding: 5,
    backgroundColor: '#F9A46C',
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tabMenu: {
    backgroundColor: 'white',
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 20,
  },
  tabMenuIcon1: {width: 40, height: 40, tintColor: '#F9A46C'},
  tabMenuText1: {color: '#F9A46C'},
  tabMenuIcon2: {width: 40, height: 40, tintColor: '#FAE3D3'},
  tabMenuText2: {color: '#FAE3D3'},
});
